addressMode: "IMP"ort Uragirimono from "uragirimono";

export default class CPU {

    /**
     * 
     * @param {Uragirimono} uragirmono 
     */
     constructor(uragirmono) {
    }

    run() {}

}

/**
 * Lookup table from https://github.com/OneLoneCoder/olcNES/blob/master/Part%232%20-%20CPU/olc6502.h (Thanks OLC!)
 */
const lookup =
	[
		{ name: "BRK", func: BRK, addressMode: "IMM", cycles: 7 },{ name: "ORA", func: ORA, addressMode: "IZX", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 3 },{ name: "ORA", func: ORA, addressMode: "ZP0", cycles: 3 },{ name: "ASL", func: ASL, addressMode: "ZP0", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 5 },{ name: "PHP", func: PHP, addressMode: "IMP", cycles: 3 },{ name: "ORA", func: ORA, addressMode: "IMM", cycles: 2 },{ name: "ASL", func: ASL, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "ORA", func: ORA, addressMode: "ABS", cycles: 4 },{ name: "ASL", func: ASL, addressMode: "ABS", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },
		{ name: "BPL", func: BPL, addressMode: "REL", cycles: 2 },{ name: "ORA", func: ORA, addressMode: "IZY", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "ORA", func: ORA, addressMode: "ZPX", cycles: 4 },{ name: "ASL", func: ASL, addressMode: "ZPX", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },{ name: "CLC", func: CLC, addressMode: "IMP", cycles: 2 },{ name: "ORA", func: ORA, addressMode: "ABY", cycles: 4 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "ORA", func: ORA, addressMode: "ABX", cycles: 4 },{ name: "ASL", func: ASL, addressMode: "ABX", cycles: 7 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },
		{ name: "JSR", func: JSR, addressMode: "ABS", cycles: 6 },{ name: "AND", func: AND, addressMode: "IZX", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "BIT", func: BIT, addressMode: "ZP0", cycles: 3 },{ name: "AND", func: AND, addressMode: "ZP0", cycles: 3 },{ name: "ROL", func: ROL, addressMode: "ZP0", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 5 },{ name: "PLP", func: PLP, addressMode: "IMP", cycles: 4 },{ name: "AND", func: AND, addressMode: "IMM", cycles: 2 },{ name: "ROL", func: ROL, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "BIT", func: BIT, addressMode: "ABS", cycles: 4 },{ name: "AND", func: AND, addressMode: "ABS", cycles: 4 },{ name: "ROL", func: ROL, addressMode: "ABS", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },
		{ name: "BMI", func: BMI, addressMode: "REL", cycles: 2 },{ name: "AND", func: AND, addressMode: "IZY", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "AND", func: AND, addressMode: "ZPX", cycles: 4 },{ name: "ROL", func: ROL, addressMode: "ZPX", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },{ name: "SEC", func: SEC, addressMode: "IMP", cycles: 2 },{ name: "AND", func: AND, addressMode: "ABY", cycles: 4 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "AND", func: AND, addressMode: "ABX", cycles: 4 },{ name: "ROL", func: ROL, addressMode: "ABX", cycles: 7 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },
		{ name: "RTI", func: RTI, addressMode: "IMP", cycles: 6 },{ name: "EOR", func: EOR, addressMode: "IZX", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 3 },{ name: "EOR", func: EOR, addressMode: "ZP0", cycles: 3 },{ name: "LSR", func: LSR, addressMode: "ZP0", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 5 },{ name: "PHA", func: PHA, addressMode: "IMP", cycles: 3 },{ name: "EOR", func: EOR, addressMode: "IMM", cycles: 2 },{ name: "LSR", func: LSR, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "JMP", func: JMP, addressMode: "ABS", cycles: 3 },{ name: "EOR", func: EOR, addressMode: "ABS", cycles: 4 },{ name: "LSR", func: LSR, addressMode: "ABS", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },
		{ name: "BVC", func: BVC, addressMode: "REL", cycles: 2 },{ name: "EOR", func: EOR, addressMode: "IZY", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "EOR", func: EOR, addressMode: "ZPX", cycles: 4 },{ name: "LSR", func: LSR, addressMode: "ZPX", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },{ name: "CLI", func: CLI, addressMode: "IMP", cycles: 2 },{ name: "EOR", func: EOR, addressMode: "ABY", cycles: 4 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "EOR", func: EOR, addressMode: "ABX", cycles: 4 },{ name: "LSR", func: LSR, addressMode: "ABX", cycles: 7 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },
		{ name: "RTS", func: RTS, addressMode: "IMP", cycles: 6 },{ name: "ADC", func: ADC, addressMode: "IZX", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 3 },{ name: "ADC", func: ADC, addressMode: "ZP0", cycles: 3 },{ name: "ROR", func: ROR, addressMode: "ZP0", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 5 },{ name: "PLA", func: PLA, addressMode: "IMP", cycles: 4 },{ name: "ADC", func: ADC, addressMode: "IMM", cycles: 2 },{ name: "ROR", func: ROR, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "JMP", func: JMP, addressMode: "IND", cycles: 5 },{ name: "ADC", func: ADC, addressMode: "ABS", cycles: 4 },{ name: "ROR", func: ROR, addressMode: "ABS", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },
		{ name: "BVS", func: BVS, addressMode: "REL", cycles: 2 },{ name: "ADC", func: ADC, addressMode: "IZY", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "ADC", func: ADC, addressMode: "ZPX", cycles: 4 },{ name: "ROR", func: ROR, addressMode: "ZPX", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },{ name: "SEI", func: SEI, addressMode: "IMP", cycles: 2 },{ name: "ADC", func: ADC, addressMode: "ABY", cycles: 4 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "ADC", func: ADC, addressMode: "ABX", cycles: 4 },{ name: "ROR", func: ROR, addressMode: "ABX", cycles: 7 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },
		{ name: "???", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "STA", func: STA, addressMode: "IZX", cycles: 6 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },{ name: "STY", func: STY, addressMode: "ZP0", cycles: 3 },{ name: "STA", func: STA, addressMode: "ZP0", cycles: 3 },{ name: "STX", func: STX, addressMode: "ZP0", cycles: 3 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 3 },{ name: "DEY", func: DEY, addressMode: "IMP", cycles: 2 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "TXA", func: TXA, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "STY", func: STY, addressMode: "ABS", cycles: 4 },{ name: "STA", func: STA, addressMode: "ABS", cycles: 4 },{ name: "STX", func: STX, addressMode: "ABS", cycles: 4 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 4 },
		{ name: "BCC", func: BCC, addressMode: "REL", cycles: 2 },{ name: "STA", func: STA, addressMode: "IZY", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },{ name: "STY", func: STY, addressMode: "ZPX", cycles: 4 },{ name: "STA", func: STA, addressMode: "ZPX", cycles: 4 },{ name: "STX", func: STX, addressMode: "ZPY", cycles: 4 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 4 },{ name: "TYA", func: TYA, addressMode: "IMP", cycles: 2 },{ name: "STA", func: STA, addressMode: "ABY", cycles: 5 },{ name: "TXS", func: TXS, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 5 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 5 },{ name: "STA", func: STA, addressMode: "ABX", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 5 },
		{ name: "LDY", func: LDY, addressMode: "IMM", cycles: 2 },{ name: "LDA", func: LDA, addressMode: "IZX", cycles: 6 },{ name: "LDX", func: LDX, addressMode: "IMM", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },{ name: "LDY", func: LDY, addressMode: "ZP0", cycles: 3 },{ name: "LDA", func: LDA, addressMode: "ZP0", cycles: 3 },{ name: "LDX", func: LDX, addressMode: "ZP0", cycles: 3 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 3 },{ name: "TAY", func: TAY, addressMode: "IMP", cycles: 2 },{ name: "LDA", func: LDA, addressMode: "IMM", cycles: 2 },{ name: "TAX", func: TAX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "LDY", func: LDY, addressMode: "ABS", cycles: 4 },{ name: "LDA", func: LDA, addressMode: "ABS", cycles: 4 },{ name: "LDX", func: LDX, addressMode: "ABS", cycles: 4 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 4 },
		{ name: "BCS", func: BCS, addressMode: "REL", cycles: 2 },{ name: "LDA", func: LDA, addressMode: "IZY", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 5 },{ name: "LDY", func: LDY, addressMode: "ZPX", cycles: 4 },{ name: "LDA", func: LDA, addressMode: "ZPX", cycles: 4 },{ name: "LDX", func: LDX, addressMode: "ZPY", cycles: 4 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 4 },{ name: "CLV", func: CLV, addressMode: "IMP", cycles: 2 },{ name: "LDA", func: LDA, addressMode: "ABY", cycles: 4 },{ name: "TSX", func: TSX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 4 },{ name: "LDY", func: LDY, addressMode: "ABX", cycles: 4 },{ name: "LDA", func: LDA, addressMode: "ABX", cycles: 4 },{ name: "LDX", func: LDX, addressMode: "ABY", cycles: 4 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 4 },
		{ name: "CPY", func: CPY, addressMode: "IMM", cycles: 2 },{ name: "CMP", func: CMP, addressMode: "IZX", cycles: 6 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "CPY", func: CPY, addressMode: "ZP0", cycles: 3 },{ name: "CMP", func: CMP, addressMode: "ZP0", cycles: 3 },{ name: "DEC", func: DEC, addressMode: "ZP0", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 5 },{ name: "INY", func: INY, addressMode: "IMP", cycles: 2 },{ name: "CMP", func: CMP, addressMode: "IMM", cycles: 2 },{ name: "DEX", func: DEX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "CPY", func: CPY, addressMode: "ABS", cycles: 4 },{ name: "CMP", func: CMP, addressMode: "ABS", cycles: 4 },{ name: "DEC", func: DEC, addressMode: "ABS", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },
		{ name: "BNE", func: BNE, addressMode: "REL", cycles: 2 },{ name: "CMP", func: CMP, addressMode: "IZY", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "CMP", func: CMP, addressMode: "ZPX", cycles: 4 },{ name: "DEC", func: DEC, addressMode: "ZPX", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },{ name: "CLD", func: CLD, addressMode: "IMP", cycles: 2 },{ name: "CMP", func: CMP, addressMode: "ABY", cycles: 4 },{ name: "NOP", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "CMP", func: CMP, addressMode: "ABX", cycles: 4 },{ name: "DEC", func: DEC, addressMode: "ABX", cycles: 7 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },
		{ name: "CPX", func: CPX, addressMode: "IMM", cycles: 2 },{ name: "SBC", func: SBC, addressMode: "IZX", cycles: 6 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "CPX", func: CPX, addressMode: "ZP0", cycles: 3 },{ name: "SBC", func: SBC, addressMode: "ZP0", cycles: 3 },{ name: "INC", func: INC, addressMode: "ZP0", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 5 },{ name: "INX", func: INX, addressMode: "IMP", cycles: 2 },{ name: "SBC", func: SBC, addressMode: "IMM", cycles: 2 },{ name: "NOP", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "???", func: SBC, addressMode: "IMP", cycles: 2 },{ name: "CPX", func: CPX, addressMode: "ABS", cycles: 4 },{ name: "SBC", func: SBC, addressMode: "ABS", cycles: 4 },{ name: "INC", func: INC, addressMode: "ABS", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },
		{ name: "BEQ", func: BEQ, addressMode: "REL", cycles: 2 },{ name: "SBC", func: SBC, addressMode: "IZY", cycles: 5 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 8 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "SBC", func: SBC, addressMode: "ZPX", cycles: 4 },{ name: "INC", func: INC, addressMode: "ZPX", cycles: 6 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 6 },{ name: "SED", func: SED, addressMode: "IMP", cycles: 2 },{ name: "SBC", func: SBC, addressMode: "ABY", cycles: 4 },{ name: "NOP", func: NOP, addressMode: "IMP", cycles: 2 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },{ name: "???", func: NOP, addressMode: "IMP", cycles: 4 },{ name: "SBC", func: SBC, addressMode: "ABX", cycles: 4 },{ name: "INC", func: INC, addressMode: "ABX", cycles: 7 },{ name: "???", func: XXX, addressMode: "IMP", cycles: 7 },
    ];